name: caddy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/caddy.yaml'
  schedule:
    - cron: "0 0 * * Sat"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]  # 支持多架构的构建

    steps:
      # Setup Go environment
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true

      # Check if go.mod exists, if not, initialize go module
      - name: Initialize Go module
        run: |
          if [ ! -f go.mod ]; then
            go mod init github.com/yourrepo/yourproject
          fi

      # Generate go.sum
      - name: Generate go.sum
        run: go mod tidy

      # Install xcaddy
      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      # Build Caddy with plugins
      - name: Build Caddy with plugins
        run: |
          CaddyVer=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)
          echo "CaddyVer=${CaddyVer}" >> $GITHUB_ENV
          xcaddy build latest \
            --with github.com/imgk/caddy-trojan \
            --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
            --output caddy_linux-${{ matrix.arch }}
          zstd -k -19 caddy_linux-${{ matrix.arch }} -o caddy_linux-${{ matrix.arch }}.zst

      # Upload built artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: caddy-${{ matrix.arch }}
          path: ./caddy_linux-${{ matrix.arch }}.zst

  release:
    runs-on: ubuntu-latest
    needs: build  # 确保发布任务依赖于构建任务完成
    steps:
      # Upload release to GitHub
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CaddyVer }}  # 确保 tag 被正确传递
          body: Caddy ${{ env.CaddyVer }} with Trojan and Forwardproxy
          file: ./caddy_linux-*.zst
          overwrite: true
          file_glob: true
