name: caddy

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/caddy.yaml'
  schedule:
    - cron: "0 0 * * Sat"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@master
      with:
        check-latest: true

    - name: install
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: xcaddy
      run: |
        export version=$(curl -s "https://api.github.com/repos/caddyserver/caddy/releases/latest" | jq -r .tag_name)
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        echo CaddyVer=${version} >>$GITHUB_ENV
        for arch in amd64 arm64
        do
          env GOOS=linux GOARCH=${arch} xcaddy build latest \
          --with github.com/imgk/caddy-trojan \
          --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive \
          --output caddy_linux-${arch}
        zstd -k -19 caddy_linux-${arch} -o caddy_linux-${arch}.zst
        done

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: caddy
        path: ./

    - name: fin
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.CaddyVer }}
        body: caddy ${{ env.CaddyVer }} w/ trojan n forwardproxy
        file: ./caddy_linux-*
        overwrite: true
        file_glob: true
